<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Emits an INSERT-only SQL dump of the current database, formatted for
 * loading into PostgreSQL. Used during the SQLite → Postgres migration
 * (see docs/ops/postgres-migration.md).
 *
 *   php artisan db:dump-for-postgres > /tmp/cihrms.sql
 *   php artisan db:dump-for-postgres --tables=users,employees
 *
 * Quoting rules applied:
 *   - column / table identifiers in double-quotes
 *   - booleans as `true` / `false` (not 1 / 0)
 *   - NULL as the bare token `NULL`
 *   - strings escaped via dollar-quoting so apostrophes survive
 *
 * Does NOT dump schema — `php artisan migrate --force` runs first on the
 * target Postgres database and produces an empty but correct schema. Then
 * this dump is replayed to populate it.
 */
class DumpForPostgres extends Command
{
    protected $signature = 'db:dump-for-postgres
                            {--tables= : Comma-separated list of tables to include (default: all)}
                            {--exclude=cache,jobs,job_batches,failed_jobs,sessions : Comma-separated tables to skip}';

    protected $description = 'Emit INSERT-only SQL dump of the current DB, Postgres-formatted.';

    public function handle(): int
    {
        $only    = array_filter(array_map('trim', explode(',', (string) $this->option('tables'))));
        $exclude = array_filter(array_map('trim', explode(',', (string) $this->option('exclude'))));

        $tables = $this->listTables();
        if (! empty($only)) {
            $tables = array_values(array_intersect($tables, $only));
        }
        $tables = array_values(array_diff($tables, $exclude));

        $this->output->writeln('-- Generated by db:dump-for-postgres on ' . now()->toIso8601String());
        $this->output->writeln('SET session_replication_role = replica;'); // disable FK checks during load

        foreach ($tables as $table) {
            $this->dumpTable($table);
        }

        $this->output->writeln('SET session_replication_role = DEFAULT;');
        return self::SUCCESS;
    }

    private function dumpTable(string $table): void
    {
        $cols = Schema::getColumnListing($table);
        if (empty($cols)) return;

        $quotedCols = array_map(fn ($c) => '"' . $c . '"', $cols);

        DB::table($table)->orderBy($cols[0])->chunk(500, function ($rows) use ($table, $cols, $quotedCols) {
            foreach ($rows as $row) {
                $values = [];
                foreach ($cols as $col) {
                    $values[] = $this->literal($row->{$col} ?? null);
                }
                $this->output->writeln(sprintf(
                    'INSERT INTO "%s" (%s) VALUES (%s);',
                    $table,
                    implode(', ', $quotedCols),
                    implode(', ', $values),
                ));
            }
        });
    }

    private function literal(mixed $value): string
    {
        if ($value === null) return 'NULL';
        if (is_bool($value)) return $value ? 'true' : 'false';
        if (is_int($value) || is_float($value)) return (string) $value;

        // Most JSON columns arrive here as a JSON string; treat them like any
        // other string. Postgres' `json` and `jsonb` types accept text that
        // happens to be valid JSON when cast at INSERT time.
        $s = (string) $value;

        // Dollar-quoting sidesteps apostrophe escaping entirely. The tag is
        // randomised per row so it can never appear inside the data.
        $tag = 'cihrms_' . substr(md5($s . microtime(true)), 0, 8);
        return "\$" . $tag . "\$" . $s . "\$" . $tag . "\$";
    }

    /**
     * Returns the list of base table names for the active connection. Uses
     * Laravel's portable Schema::getTables() (introduced in 11.x) and falls
     * back to driver-specific information_schema queries for older versions.
     */
    private function listTables(): array
    {
        if (method_exists(Schema::class, 'getTables')) {
            return array_values(array_unique(array_map(
                fn ($t) => is_array($t) ? ($t['name'] ?? '') : (string) $t,
                Schema::getTables(),
            )));
        }

        $driver = DB::connection()->getDriverName();
        return match ($driver) {
            'sqlite' => array_column(
                DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"),
                'name',
            ),
            'pgsql' => array_column(
                DB::select("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name"),
                'table_name',
            ),
            'mysql', 'mariadb' => array_map(
                fn ($r) => (array) $r,
                DB::select('SHOW TABLES'),
            ) ? array_map(fn ($r) => current((array) $r), DB::select('SHOW TABLES')) : [],
            default => [],
        };
    }
}
